[package]
name = "rtoy-samples"
version = "0.1.0"
authors = ["Tomasz Stachowiak <h3@h3.gd>"]
edition = "2018"

description = "Shader include parser and crawler"
readme = "README.md"
license = "MIT"
repository = "https://github.com/h3r2tic/rtoy-samples"

[dependencies]
#rendertoy = { git = "https://github.com/h3r2tic/rendertoy" }
rendertoy = { path = "../rendertoy" }
#rtoy-rt = { git = "https://github.com/h3r2tic/rtoy-rt" }
rtoy-rt = { path = "../rtoy-rt" }
snoozy = { git = "https://github.com/h3r2tic/snoozy" }
snoozy-macros = { git = "https://github.com/h3r2tic/snoozy-macros" }
#snoozy = { path = "../snoozy" }
rand = "0.6.5"
aliasmethod = { git = "https://github.com/h3r2tic/rust_aliasmethod" }