[package]
name = "rtoy-samples"
version = "0.1.0"
authors = ["Tomasz Stachowiak <h3@h3.gd>"]
edition = "2018"

description = "Shader include parser and crawler"
readme = "README.md"
license = "MIT"
repository = "https://github.com/h3r2tic/rtoy-samples"

[dependencies]
rendertoy = { git = "https://github.com/h3r2tic/rendertoy" }
#rendertoy = { path = "../rendertoy" }
nalgebra = "0.17"
obj-rs = "0.4"
bvh = { git = "https://github.com/h3r2tic/bvh", rev = "afbaaddfd15344a5e422183ac567263e3c21a08d" }
static_assertions = "0.3.1"
rust-lzma = "0.4.0"