[package]
name = "rtoy-samples"
version = "0.1.0"
authors = ["Tomasz Stachowiak <h3@h3.gd>"]
edition = "2018"

description = "Shader include parser and crawler"
readme = "README.md"
license = "MIT"
repository = "https://github.com/h3r2tic/rtoy-samples"

[dependencies]
rendertoy = { git = "https://github.com/h3r2tic/rendertoy" }
#rendertoy = { path = "../rendertoy" }
rtoy-rt = { git = "https://github.com/h3r2tic/rtoy-rt" }
#rtoy-rt = { path = "../rtoy-rt" }
rand = "0.6.5"
snoozy = { git = "https://github.com/h3r2tic/snoozy" }
#serde = "1.0.80"
#serde_derive = "1.0"